// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: outputer/v1/outputer.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Outputer_Write_FullMethodName = "/outputer.v1.Outputer/Write"
)

// OutputerClient is the client API for Outputer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OutputerClient interface {
	Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type outputerClient struct {
	cc grpc.ClientConnInterface
}

func NewOutputerClient(cc grpc.ClientConnInterface) OutputerClient {
	return &outputerClient{cc}
}

func (c *outputerClient) Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Outputer_Write_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OutputerServer is the server API for Outputer service.
// All implementations must embed UnimplementedOutputerServer
// for forward compatibility.
type OutputerServer interface {
	Write(context.Context, *WriteRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedOutputerServer()
}

// UnimplementedOutputerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOutputerServer struct{}

func (UnimplementedOutputerServer) Write(context.Context, *WriteRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedOutputerServer) mustEmbedUnimplementedOutputerServer() {}
func (UnimplementedOutputerServer) testEmbeddedByValue()                  {}

// UnsafeOutputerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OutputerServer will
// result in compilation errors.
type UnsafeOutputerServer interface {
	mustEmbedUnimplementedOutputerServer()
}

func RegisterOutputerServer(s grpc.ServiceRegistrar, srv OutputerServer) {
	// If the following call pancis, it indicates UnimplementedOutputerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Outputer_ServiceDesc, srv)
}

func _Outputer_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutputerServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Outputer_Write_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutputerServer).Write(ctx, req.(*WriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Outputer_ServiceDesc is the grpc.ServiceDesc for Outputer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Outputer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "outputer.v1.Outputer",
	HandlerType: (*OutputerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Write",
			Handler:    _Outputer_Write_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "outputer/v1/outputer.proto",
}
